# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-22 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181222_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 3, 23, 39, 276438, tzinfo=utc)),
        ),
    ]
