# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-22 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20181222_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 5, 55, 0, 412438, tzinfo=utc)),
        ),
    ]
