# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-23 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181222_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 12, 14, 50, 495604, tzinfo=utc)),
        ),
    ]
